---
- hosts: localhost
  become: yes

  vars:
    netbox_version: 3.7.5
    postgres_password: simple_password
    allowed_hosts: "'10.*'"
    postgres_user: "netbox"
  
  tasks:
    - name: Install required packages
      apt:
        name:
          - postgresql
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          - build-essential
          - libxml2-dev
          - libxslt1-dev
          - libffi-dev
          - libpq-dev
          - libssl-dev
          - zlib1g-dev
          - redis-server
        state: present

    - name: Install libpq-dev
      apt:
        name: libpq-dev
        state: present

    - name: Install psycopg2 using pip
      pip:
        name: psycopg2

    - name: Create netbox user
      become: yes
      become_user: postgres
      postgresql_user:
        name: netbox
        password: "{{ postgres_password }}"
        role_attr_flags: CREATEDB

    - name: Create netbox database
      become: yes
      become_user: postgres
      postgresql_db:
        name: netbox
        owner: netbox

    - name: Grant privileges
      become: yes
      become_user: postgres
      postgresql_privs:
        db: netbox
        type: table
        roles: netbox
        privs: CREATE
        objs: ALL_IN_SCHEMA

    - name: Create netbox group
      group:
        name: netbox
        system: yes

    - name: Create netbox user and group
      user:
        name: netbox
        group: netbox
        system: yes
        
    - name: Create directory /opt/netbox and change owner to netbox
      file:
        path: /opt/netbox
        state: directory
        owner: netbox
        group: netbox
        mode: '0755'

    - name: Clone netbox git repo
      become: yes
      become_user: netbox
      git:
        repo: 'https://github.com/netbox-community/netbox.git'
        dest: /opt/netbox
        version: master
        depth: 1

    - name: Remove contents of /home/netbox/.ansible directory
      file:
        path: /home/netbox/.ansible
        state: absent
      become: yes
      become_user: netbox

    - name: Check if configuration.py exists and get SECRET_KEY
      shell: grep ^SECRET_KEY /opt/netbox/netbox/netbox/netbox/configuration.py | cut -d "'" -f 2
      register: secret_key
      ignore_errors: yes
      changed_when: false

    - name: Display the contents of secret_key
      debug: 
        msg: secret_key.stdout 
      when: secret_key.stdout == ""


    - name: Generate secret key if not exist
      command: python3 /opt/netbox/netbox/generate_secret_key.py
      register: generated_secret_key
      when: secret_key.stdout == ""

    - name: Set secret_key variable
      set_fact:
        secret_key: "{{ generated_secret_key.stdout }}"
      when: secret_key.stdout == ""

    - name: Copy configuration.py.j2 to configuration.py
      template:
        src: ./configuration.py.j2
        dest: /opt/netbox/netbox/netbox/configuration.py
        owner: netbox
        group: netbox
        mode: '0644'
      vars:
        secret_key: "{{ secret_key.stdout }}"
